source 'https://github.com/CocoaPods/Specs.git'


def import_pods
	pod "RPOTCMPerformOperationToCompletionManager", :path => "../"
	pod 'FXReachability', '1.3'
end


target 'RPOTCMPerformOperationToCompletionManager_Example', :exclusive => true do
	import_pods
end


target 'RPOTCMPerformOperationToCompletionManager_Tests', :exclusive => true do
	import_pods
	pod 'Specta'
	pod 'Expecta'
	pod 'FBSnapshotTestCase'
	pod 'Expecta+Snapshots'
end
