source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '7.0'

target 'RPOTCMPerformOperationToCompletionManager_Example', :exclusive => true do
  pod "RPOTCMPerformOperationToCompletionManager", :path => "../"
  
  pod 'FXReachability', '1.3'
end

target 'RPOTCMPerformOperationToCompletionManager_Tests', :exclusive => true do
  pod "RPOTCMPerformOperationToCompletionManager", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
