use_frameworks!

target 'RPOTCMPerformOperationToCompletionManager_Example' do
  pod 'RPOTCMPerformOperationToCompletionManager', :path => '../'

  target 'RPOTCMPerformOperationToCompletionManager_Tests' do
    inherit! :search_paths

    
  end
end
